### ISSUE TITLE
Problem with your definition of censorship.

### ISSUE THREAD

**Issue by joaopaulo-cerquinhocajueiro** [rosarior/Code-of-Merit#2]
Great code. Sadly necessary.
I have a problem with you saying that censorship will not be permitted but saying that many things are not allowed. I think you are afraid of the word. Why don't you just say:
- Non technical issues will be censored.
- World politics comments will be censored.
- The mention of differences will be censored. Everybody is different, but this is not technically relevant.
- Unless your project depends on miracles, religion is technically irrelevant. Religious comments will be censored.

**Comment by poldy** [comment]
+1

This is an old problem. The Royal Society solved it by banning discussion of religion or politics (given that humans are social animals, politics can be interpreted much more broadly than Left versus Right) about 350 years ago.

"When (to avoid diversion to other discourses, and for some other reasons), we barred all discourses of divinity, of state affairs, and of news, other than what concerned our business of Philosophy."

Paragraph 5 of https://legacy.fordham.edu/halsall/mod/1662royalsociety.asp

**Comment by rosarior** [comment]
> Great code. Sadly necessary.

Thank you. I sadly agree too.

> I have a problem

Leave your problems at the door, I'm only interested in solutions, suggestions, ideas.

> with you saying that censorship will not be permitted but saying that many things are not allowed.

Muting things that are not relevant to the technical problems at hand is not censorship, it is avoiding noise.

> I think you are afraid of the word.

You can think anything you want about me, I'm not interested in hearing, it is not relevant to the discussion.

> Non technical issues will be censored.
> World politics comments will be censored.
> The mention of differences will be censored. Everybody is different, but this is not technically relevant.
> Unless your project depends on miracles, religion is technically irrelevant. Religious comments will be censored.

"This is a space for technical prowess; world politics have no place here." 

---
Paragraph 5 of https://legacy.fordham.edu/halsall/mod/1662royalsociety.asp
"we barred all discourses of divinity, of state affairs, and of news,"
I like the spirit of it, but by explicitly mentioning non allowed topics, leaves the opportunity for new topic or made up topics, which is why we are having this code of conduct problem in the first place. I will try to incorporate the purpose behind this paragraph in an all inclusive manner.
